language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t openusm/openusm .
  

before_script:
  - pip install requests
 
travis env set DOCKER_USERNAME openusm
travis env set DOCKER_PASSWORD Oracle9ias

script:
  - python bios-token.py --help
