language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t openusm/openusm .
  

before_script:
  - pip install requests
 
env:
  global:
    - secure: "DO68Qy37KVb6aMxISeg4hGTHJMuA8Rc2G4oH5LF1ooY2p4AJ78UJG2EexQ0BX3i33dclYwr/vlzdRxy0tccRGxz6C6s6WHbThfw7x/AwGJSEamoGj0ETb
vcNnDRWiC5GL3Mpu5orujidxrDV+xsEizk9sEjsR1VBXupLT4+nO4hoxRmaBWrq/+SA1XubXdq98xQ/kJdX4+IbiSj15JB+7L/53aK+kUhvWS+unT5qIEwkiVbGC8dmt
R4DKm2WwJluFwpX6GH0I5QNOKjUqm+Ld28/i0IUcI8xLgZNVnAv+uFvZICxU+jnydJxSyFZxBQiCoSmDQeQtnau4k2bElgYpy4o2N8lWZ3N/BMzpdViPmzZ5putXTU6i
vB0fzO1kg1TleiKx3+FyDmXNhep8gp4DskcgGyF6c9IDZboAU3m/i8HZkDq8BZk+Bk0PAZJbN3Yy6wi+FuBommCIspUBXEXHNN9dSbvHU8ZPkEz9HSQASyPMqwKz17lb
WuVWBRksNdpAShQGljgP+kPOGWEvAeN4f/Ng9EXXZ/VrjHx2IJS25PMqUriBNSodD7az1sslVylN+i+xNNh75U6+cenVbAXS+0rfejeOWZXyi+IIfJXOLCX6yfI5+bc9
DBLQ7mvOHi5Y4jFQmQeyZQHTnRPU+xLgBbrL7fxSykt5D1UIjaw4IY=" # DOCKER_EMAIL
    - secure: "UKfKAO+yb+wUl3qbYWgJSxXJjKVkRsOAgSRhjbc1SUhr82HUrv7ZgrzpyfB8j8/g4oE2FLGZmpafewjQlvCilYSZNENcweDEcLNQ/13GLNUXs80FJ3aR3
f7utB76vLbOim8cNc5qI5p7cZi1ng1kKIKbIKRIG9/3OK/q8DDJDF451OOcHkQgP+RaMKkNs62fhWwe+sEKUtW0wMi5SzE9n0gQihUj1NzzzwED3m2e39xfJVmVUVUl3
OIfBNM45AwC52cKdfHfOeIyUaF2Rk9IQ/GwM265ITEBxv1KE2labQX942Nfm6r2XGt1xR3F3yR6VXg3d71G0Yo5oR8O6Twrnjl31CYrEmxgd98ztSVYq4x72bNOJe1k2
X6wXaCQ0lHyzqHQQRzJ4b3jwJV9ROPf/rgToJHGX0MOJERYC51i+pyxvPpFXClp8uiluDjycM6k98zGEcK43PsUiqKeuG/JWkURenrLVtyyPbUe8PWUmhJPgP4cD/QzM
DumfV0bttUcGEsOgjdincbTv1VmnOjbMx29hl5VusizXJSXTPOhtuVfQ548FN+MO+tYLey+GE9IbN9PX7GaSIYcjnsn4zt7+WDbncupOzRzIMk7JP2bDVGZxcj2sQUR9
cAUZd4AewtkHsZhxn63qNfVXFj7RsEEv1a5z5JyvV634v0TZdwGPj8=" # DOCKER_USER
    - secure: "NEyrzHPtpCes11gg6pz8WgeghHIPbJ6G+hy3vQepSftWv04ylj1nI9piIHcMkH0D0yhc2WJC5vfDQ9/ml7fKhUasRbXFxpI3UKkUpDGB5uWrRZgMufd+J
wcQr9bjmXTQg2zymqoJfcQV5uBxCMJSxXbgqpyzCEvxzYUSdtQgOI5O6Tgze4bRfpnmOiK7x6lXcKfSv5o0XZFe12N4Htgvv6HNx3EOTh1/SK/Me0ty9+h07chSss5Rz
6GOhQ63LQiGM1jBhGiipnsbTjnnulHSwVZhjabkMxy2GPFxqA39cC6ukZZ9JcCEyZRg1mLTMkQvFphsYPa+jYkQauWZFmSOO9BQpUMig2wBGzPWIff56X0v2S03E7Oj0dqdvcFVxaWibXtEgaJZnZ51CUz9MlOrmCmEzTxBROAg/nk/hP/sJh9ooqtjRtF4VjcjEaQWhV6NfjOLl/brN0Ajmcn5JPxZvo9y78HRpQeuqmSc1Cfe9aXQf7WXJl56d0hd51VXMp4hv9JMlND619zBFk4UAtoe2Sm858G61W052RipN+vgdPX8p62wNl5J+5v965tIlc5nEmZr8U5xUw+QyD+9FiZUFA0y/KqyUZ+CjiVm7gn33VCkZduDxH1tFcUTz1TvhiiLsTAMV3Ud2e09jey5JJC0oz1uf326q8DytrBDGj1F6GQ=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8} 
 
script:
  - python bios-token.py --help
