language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t openusm/openusm .
  

before_script:
  - pip install -r requirements.txt
  - pip install mock
  - pip install requests
 

script:
  - python bios-token.py --help
