language: python
python:
  - 2.7

services:
  - docker

install:
  - docker build -t openusm/openusm .
  

before_script:
  - pip install requests
 
env:
  global:
    - secure: "r40cyUp4N/fSwo+xYaRjKWHGgHbH5AgFwQ2wZCHjacWS4J15LZF2591kXLBKmoj5Kslfo6LgBQLY8MVBBnBDKo+q0rGJQbzE8GZRyCHacexZND7PRQo9sn5QonkWeAlIrE058IVgNG8Fqh+9XPKGUjAIp8tmybPM7JQ5BVLcK5H51FCnwx3xWBzkdU7NLarf6QqrthsD2ePsrc2y7yI52tkpZOE2cr66jrEqZzcT4aqModiBiM3Hr
msWTNF7Mrg3yQWREz8rC4/ZbUxTI7dh5SUyXD2Ol915ytr6lxvANeKcBQ38Xrx+a/FWk6hzEbvEP2SYh6YhIMnJbR3viLEpJHyIhFfFxNJQqaKoKrfXja68i07WMY4jw
wAnFm/9JJxIpF8c55D7SRztCC1h9igPeirTqMwQuvRuwXfV/Yz+93Tczf6tDGvtCKYkfuveKQhtbqZM/XrBtkCG4hPryr/PZlxAHT8vsIoFneliCjtZoYxKHufgo9Dty
jcgryUopw0HAYShPTE2c3TL763d52c+a4A/7IaZ+e+2QFpqwwOi1qv7OKDGh5MW7jRO0gNGPXYfejKn8nelopUbaasvSvJdkxbTo74YhFPM6ECO9wYvdLOCBgXo1Ke/s
/1blYtdqI9KOP34Equuzay0RAEnudK9e5ftVdbFtSu8o+VWHaIqCto=" # DOCKER_EMAIL
    - secure: "UKfKAO+yb+wUl3qbYWgJSxXJjKVkRsOAgSRhjbc1SUhr82HUrv7ZgrzpyfB8j8/g4oE2FLGZmpafewjQlvCilYSZNENcweDEcLNQ/13GLNUXs80FJ3aR3
f7utB76vLbOim8cNc5qI5p7cZi1ng1kKIKbIKRIG9/3OK/q8DDJDF451OOcHkQgP+RaMKkNs62fhWwe+sEKUtW0wMi5SzE9n0gQihUj1NzzzwED3m2e39xfJVmVUVUl3
OIfBNM45AwC52cKdfHfOeIyUaF2Rk9IQ/GwM265ITEBxv1KE2labQX942Nfm6r2XGt1xR3F3yR6VXg3d71G0Yo5oR8O6Twrnjl31CYrEmxgd98ztSVYq4x72bNOJe1k2
X6wXaCQ0lHyzqHQQRzJ4b3jwJV9ROPf/rgToJHGX0MOJERYC51i+pyxvPpFXClp8uiluDjycM6k98zGEcK43PsUiqKeuG/JWkURenrLVtyyPbUe8PWUmhJPgP4cD/QzM
DumfV0bttUcGEsOgjdincbTv1VmnOjbMx29hl5VusizXJSXTPOhtuVfQ548FN+MO+tYLey+GE9IbN9PX7GaSIYcjnsn4zt7+WDbncupOzRzIMk7JP2bDVGZxcj2sQUR9
cAUZd4AewtkHsZhxn63qNfVXFj7RsEEv1a5z5JyvV634v0TZdwGPj8=" # DOCKER_USER
    - secure: "NEyrzHPtpCes11gg6pz8WgeghHIPbJ6G+hy3vQepSftWv04ylj1nI9piIHcMkH0D0yhc2WJC5vfDQ9/ml7fKhUasRbXFxpI3UKkUpDGB5uWrRZgMufd+J
wcQr9bjmXTQg2zymqoJfcQV5uBxCMJSxXbgqpyzCEvxzYUSdtQgOI5O6Tgze4bRfpnmOiK7x6lXcKfSv5o0XZFe12N4Htgvv6HNx3EOTh1/SK/Me0ty9+h07chSss5Rz
6GOhQ63LQiGM1jBhGiipnsbTjnnulHSwVZhjabkMxy2GPFxqA39cC6ukZZ9JcCEyZRg1mLTMkQvFphsYPa+jYkQauWZFmSOO9BQpUMig2wBGzPWIff56X0v2S03E7Oj0dqdvcFVxaWibXtEgaJZnZ51CUz9MlOrmCmEzTxBROAg/nk/hP/sJh9ooqtjRtF4VjcjEaQWhV6NfjOLl/brN0Ajmcn5JPxZvo9y78HRpQeuqmSc1Cfe9aXQf7WXJl56d0hd51VXMp4hv9JMlND619zBFk4UAtoe2Sm858G61W052RipN+vgdPX8p62wNl5J+5v965tIlc5nEmZr8U5xUw+QyD+9FiZUFA0y/KqyUZ+CjiVm7gn33VCkZduDxH1tFcUTz1TvhiiLsTAMV3Ud2e09jey5JJC0oz1uf326q8DytrBDGj1F6GQ=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8} 
 
script:
  - python bios-token.py --help
  
  
after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=openusm/openusm
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
